### ISSUE TITLE
Clap exception in ClapContext>>pragmaCommands

### ISSUE THREAD

**Issue by Bajger** [pharo-contributions/clap-st#33]
CLAP activation currently fails. Therefore cannot run any unit test on [PharoCommandlineLauncher](https://github.com/PharoLauncherCmdLine/CommandLineLauncher) project.
```
MessageNotUnderstood: Pragma class>> #allNamed:
Pragma class(Object)>>doesNotUnderstand: #allNamed:
ClapContext class>>pragmaCommands
ClapContext class>>withPragmaCommands
[ | tmp2 |
tmp2 := ClapContext withPragmaCommands.
tmp2
	beObeyingExits;
	setStdio: Stdio;
	arguments: self arguments;
	executeToExit: [ :arg1 | self handleExit: arg1 ] ] in ClapCommandLineHandler>>activate in Block: [ | tmp2 |...
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess in Block: [ self value....
testLauncherProcessListCommandWhenNoPharoImageRunningShouldReturnEmptyList
```

**Comment by Bajger** [comment]
@demarey Hi Christophe! Can you look at this? I cannot run any unit test on PharoCommandlineLauncher.

**Comment by Bajger** [comment]
You mean to move previous implementation to this package PharoLauncher-80Compatibility, right? So is CLAP supposed to work just on P10? Or there will be a separate branch for that?

**Comment by demarey** [comment]
> You mean to move previous implementation to this package PharoLauncher-80Compatibility, right? 

yes

> So is CLAP supposed to work just on P10? Or there will be a separate branch for that?

I think it is only used in Pharo and PL for now. I'm not sure it needs a compatibility package
