### ISSUE TITLE
Running example command in image from README yields an error

### ISSUE THREAD

**Issue by capsulecorplab** [pharo-contributions/clap-st#36]
Running the following example inside image from [Defining and invoking commands](https://github.com/pharo-contributions/clap-st#defining-and-invoking-commands) yields a `Instance of ClapCommand did not understand #runWith:` error

![Screenshot from 2023-11-14 15-02-31](https://github.com/pharo-contributions/clap-st/assets/14095576/5ba3121b-3e25-4389-9bd2-b6298dfdf448)

**Comment by Bajger** [comment]
Yes, this is purely outdated documentation. Will submit PR on this. You should use `#activateWith:`  instead (see ClapCommand hiearchy).

**Comment by capsulecorplab** [comment]
Thanks @Bajger ! Using `activateWith:` seems to return an object I can inspect now.  How would I go about previewing the stdout from inspecting this object? It looks like there's a `stdio` variable, but I'm not sure how to make sense of it
![Screenshot from 2023-11-20 21-12-56](https://github.com/pharo-contributions/clap-st/assets/14095576/8366da52-de73-4684-b330-840bc62f3ca9)

**Comment by Bajger** [comment]
@capsulecorplab You can check stdout by evaluating (on context instance, which you hold inspector on screenshot): `self stdio stdout contents asString`

**Comment by capsulecorplab** [comment]
@Bajger Ah, thank you!
![Screenshot from 2023-11-21 12-04-00](https://github.com/pharo-contributions/clap-st/assets/14095576/33d44478-442b-4e40-b775-d4122deb7623)
